import 'package:path/path.dart' as p;
import 'package:yaml/yaml.dart';

/// Supported infrastructure runtime backends.
///
/// Dew starts with Podman Quadlets, but commands depend on this enum instead of
/// directly depending on Quadlet paths so additional runtimes can be introduced
/// without changing the command contract.
enum InfraRuntimeKind {
  /// Podman Quadlet files consumed by systemd.
  podmanQuadlet('podman-quadlet');

  const InfraRuntimeKind(this.id);

  /// Stable manifest identifier.
  final String id;

  static InfraRuntimeKind fromManifestValue(String? value) {
    final normalized = value ?? podmanQuadlet.id;
    return values.firstWhere(
      (kind) => kind.id == normalized,
      orElse: () => throw FormatException(
        'Unsupported infrastructure runtime "$normalized".',
      ),
    );
  }
}

/// Supported Podman Quadlet source file kinds.
enum InfraQuadletKind {
  /// Pulls an OCI artifact.
  artifact('.artifact', '-artifact'),

  /// Builds a container image from a Containerfile.
  build('.build', '-build'),

  /// Defines and manages a single container.
  container('.container', ''),

  /// Pulls and caches a container image.
  image('.image', '-image'),

  /// Deploys containers from Kubernetes YAML.
  kube('.kube', ''),

  /// Creates a Podman network.
  network('.network', '-network'),

  /// Creates a Podman pod.
  pod('.pod', '-pod'),

  /// Ensures a named Podman volume exists.
  volume('.volume', '-volume');

  const InfraQuadletKind(this.extension, this.defaultServiceSuffix);

  /// Quadlet file extension, including the leading dot.
  final String extension;

  /// Suffix Podman adds to default generated service units.
  final String defaultServiceSuffix;

  /// Stable manifest identifier.
  String get id => extension.substring(1);

  /// Finds the kind represented by [file].
  static InfraQuadletKind fromFile(String file) {
    final extension = p.extension(file);
    return values.firstWhere(
      (kind) => kind.extension == extension,
      orElse: () => throw FormatException(
        'Unsupported Quadlet file extension "$extension".',
      ),
    );
  }
}

/// A single Podman Quadlet file declared by an infrastructure service.
class InfraQuadletManifest {
  const InfraQuadletManifest({
    required this.file,
    required this.kind,
    required this.serviceDir,
    this.unit,
    this.containerName,
    this.dropinsDir,
    this.profilesDir,
  });

  /// Relative path to the Quadlet source file.
  final String file;

  /// Quadlet type inferred from [file].
  final InfraQuadletKind kind;

  /// Absolute path to the service directory.
  final String serviceDir;

  /// Optional generated systemd unit override.
  final String? unit;

  /// Optional container name for cleanup operations.
  final String? containerName;

  /// Optional relative path to the Quadlet drop-ins directory.
  final String? dropinsDir;

  /// Optional relative path to profile drop-ins.
  final String? profilesDir;

  /// Absolute path to the Quadlet source file.
  String get filePath => _resolve(file);

  /// Absolute path to the declared drop-ins directory, if any.
  String? get dropinsDirPath =>
      dropinsDir == null ? null : _resolve(dropinsDir!);

  /// Absolute path to the declared profiles directory, if any.
  String? get profilesDirPath =>
      profilesDir == null ? null : _resolve(profilesDir!);

  /// Unit name Dew should manage for this Quadlet.
  String get serviceUnit => unit ?? defaultServiceUnit;

  /// Unit name generated by Podman when the Quadlet does not override it.
  String get defaultServiceUnit {
    final baseName = p.basenameWithoutExtension(file);
    return '$baseName${kind.defaultServiceSuffix}.service';
  }

  /// Machine-readable summary.
  Map<String, Object?> toJson() => {
    'file': filePath,
    'kind': kind.id,
    'unit': serviceUnit,
    'default_unit': defaultServiceUnit,
    'container_name': containerName,
    'dropins_dir': dropinsDirPath,
    'profiles_dir': profilesDirPath,
  };

  String _resolve(String value) => p.isAbsolute(value)
      ? p.normalize(value)
      : p.normalize(p.join(serviceDir, value));
}

/// Infrastructure service metadata loaded from `manifest.yaml`.
class InfraServiceManifest {
  const InfraServiceManifest({
    required this.id,
    required this.name,
    required this.runtime,
    required this.serviceDir,
    required this.manifestPath,
    required this.quadlets,
    this.files = const [],
    this.configureSchema,
    this.initSchema,
  });

  /// Stable service identifier used on the command line.
  final String id;

  /// Human-friendly display name.
  final String name;

  /// Runtime backend declared by the manifest.
  final InfraRuntimeKind runtime;

  /// Absolute path to the service directory.
  final String serviceDir;

  /// Absolute path to `manifest.yaml`.
  final String manifestPath;

  /// Quadlet files deployed for this service.
  final List<InfraQuadletManifest> quadlets;

  /// Additional files installed beside Quadlets for build contexts or assets.
  final List<String> files;

  /// Optional relative path to the configure JSON Schema.
  final String? configureSchema;

  /// Optional relative path to the init JSON Schema.
  final String? initSchema;

  /// Absolute path to the configure schema, if any.
  String? get configureSchemaPath =>
      configureSchema == null ? null : _resolve(configureSchema!);

  /// Absolute path to the init schema, if any.
  String? get initSchemaPath =>
      initSchema == null ? null : _resolve(initSchema!);

  /// Directory for active and generated service configuration.
  String get configDir => p.join(serviceDir, 'config');

  /// Active configure payload path.
  String get activeConfigurePath => p.join(configDir, 'configure.json');

  /// Active init payload path.
  String get activeInitPath => p.join(configDir, 'init.json');

  /// Absolute paths to additional installed files.
  List<String> get filePaths => files.map(_resolve).toList();

  /// Units generated by the declared Quadlet files.
  List<String> get units =>
      quadlets.map((quadlet) => quadlet.serviceUnit).toList();

  /// Container names declared for cleanup operations.
  List<String> get containerNames => quadlets
      .map((quadlet) => quadlet.containerName)
      .whereType<String>()
      .toList();

  /// Decodes [contents] from YAML.
  factory InfraServiceManifest.parse({
    required String contents,
    required String serviceDir,
    required String manifestPath,
  }) {
    final map = _asMap(loadYaml(contents));
    final schemas = _optionalSection(map, 'schemas');
    final runtimeSection = _optionalSection(map, 'runtime');
    final quadlets = _requiredList(
      map,
      'quadlets',
    ).map((value) => _parseQuadlet(value, serviceDir: serviceDir)).toList();

    return InfraServiceManifest(
      id: _requiredString(map, 'id'),
      name: _requiredString(map, 'name'),
      runtime: InfraRuntimeKind.fromManifestValue(
        runtimeSection == null ? null : _optionalString(runtimeSection, 'type'),
      ),
      serviceDir: serviceDir,
      manifestPath: manifestPath,
      quadlets: quadlets,
      files: _optionalStringList(map, 'files'),
      configureSchema: schemas == null
          ? null
          : _optionalString(schemas, 'configure'),
      initSchema: schemas == null ? null : _optionalString(schemas, 'init'),
    );
  }

  /// Machine-readable summary.
  Map<String, Object?> toJson() => {
    'id': id,
    'name': name,
    'runtime': runtime.id,
    'manifest': manifestPath,
    'units': units,
    'quadlets': quadlets.map((quadlet) => quadlet.toJson()).toList(),
    'files': filePaths,
    'configure_schema': configureSchemaPath,
    'init_schema': initSchemaPath,
    'active_config': activeConfigurePath,
    'active_init': activeInitPath,
  };

  String _resolve(String value) => p.isAbsolute(value)
      ? p.normalize(value)
      : p.normalize(p.join(serviceDir, value));
}

InfraQuadletManifest _parseQuadlet(
  dynamic value, {
  required String serviceDir,
}) {
  if (value is! Map) {
    throw const FormatException(
      'manifest.yaml field "quadlets" must list objects.',
    );
  }
  final map = value.map((key, value) => MapEntry('$key', value));
  final file = _requiredString(map, 'file');
  return InfraQuadletManifest(
    file: file,
    kind: InfraQuadletKind.fromFile(file),
    serviceDir: serviceDir,
    unit: _optionalString(map, 'unit'),
    containerName: _optionalString(map, 'container_name'),
    dropinsDir: _optionalString(map, 'dropins_dir'),
    profilesDir: _optionalString(map, 'profiles_dir'),
  );
}

Map<String, dynamic> _asMap(dynamic value) {
  if (value is YamlMap) {
    return value.map((key, value) => MapEntry('$key', _asYamlValue(value)));
  }
  if (value is Map) {
    return value.map((key, value) => MapEntry('$key', _asYamlValue(value)));
  }
  throw const FormatException('manifest.yaml must contain a YAML object.');
}

dynamic _asYamlValue(dynamic value) {
  if (value is YamlMap || value is Map) return _asMap(value);
  if (value is YamlList) return value.map(_asYamlValue).toList();
  if (value is List) return value.map(_asYamlValue).toList();
  return value;
}

Map<String, dynamic>? _optionalSection(Map<String, dynamic> map, String key) {
  final value = map[key];
  if (value == null) return null;
  if (value is Map) {
    return value.map((key, value) => MapEntry('$key', value));
  }
  throw FormatException('manifest.yaml field "$key" must be an object.');
}

List<dynamic> _requiredList(Map<String, dynamic> map, String key) {
  final value = map[key];
  if (value is List) return value;
  throw FormatException('manifest.yaml is missing list "$key".');
}

List<String> _optionalStringList(Map<String, dynamic> map, String key) {
  final value = map[key];
  if (value == null) return const [];
  if (value is! List) {
    throw FormatException('manifest.yaml field "$key" must be a list.');
  }
  return value.map((item) {
    if (item is String && item.isNotEmpty) return item;
    throw FormatException(
      'manifest.yaml field "$key" must contain non-empty strings.',
    );
  }).toList();
}

String _requiredString(Map<String, dynamic> map, String key) {
  final value = _optionalString(map, key);
  if (value == null || value.isEmpty) {
    throw FormatException('manifest.yaml is missing required string "$key".');
  }
  return value;
}

String? _optionalString(Map<String, dynamic> map, String key) {
  final value = map[key];
  if (value == null) return null;
  if (value is String) return value;
  throw FormatException('manifest.yaml field "$key" must be a string.');
}
