import 'package:path/path.dart' as p;
import 'package:toml/toml.dart';

/// Supported infrastructure runtime backends.
///
/// Dew starts with Podman Quadlets, but commands depend on this enum instead of
/// directly depending on Quadlet paths so additional runtimes can be introduced
/// without changing the command contract.
enum InfraRuntimeKind {
  /// Podman Quadlet files consumed by systemd.
  podmanQuadlet('podman-quadlet');

  const InfraRuntimeKind(this.id);

  /// Stable manifest identifier.
  final String id;

  static InfraRuntimeKind fromManifestValue(String? value) {
    final normalized = value ?? podmanQuadlet.id;
    return values.firstWhere(
      (kind) => kind.id == normalized,
      orElse: () => throw FormatException(
        'Unsupported infrastructure runtime "$normalized".',
      ),
    );
  }
}

/// Infrastructure service metadata loaded from `metadata.toml`.
class InfraServiceManifest {
  const InfraServiceManifest({
    required this.id,
    required this.name,
    required this.unit,
    required this.containerName,
    required this.runtime,
    required this.serviceDir,
    required this.metadataPath,
    required this.containerFile,
    this.dropinsDir,
    this.profilesDir,
    this.configureSchema,
    this.initSchema,
  });

  /// Stable service identifier used on the command line.
  final String id;

  /// Human-friendly display name.
  final String name;

  /// systemd unit name generated by the runtime backend.
  final String unit;

  /// Container name used for runtime cleanup/status operations.
  final String containerName;

  /// Runtime backend declared by the manifest.
  final InfraRuntimeKind runtime;

  /// Absolute path to the service directory.
  final String serviceDir;

  /// Absolute path to `metadata.toml`.
  final String metadataPath;

  /// Relative path to the primary Quadlet/container definition.
  final String containerFile;

  /// Optional relative path to the Quadlet drop-ins directory.
  final String? dropinsDir;

  /// Optional relative path to profile drop-ins.
  final String? profilesDir;

  /// Optional relative path to the configure JSON Schema.
  final String? configureSchema;

  /// Optional relative path to the init JSON Schema.
  final String? initSchema;

  /// Absolute path to the primary container file.
  String get containerFilePath => _resolve(containerFile);

  /// Absolute path to the declared drop-ins directory, if any.
  String? get dropinsDirPath =>
      dropinsDir == null ? null : _resolve(dropinsDir!);

  /// Absolute path to the declared profiles directory, if any.
  String? get profilesDirPath =>
      profilesDir == null ? null : _resolve(profilesDir!);

  /// Absolute path to the configure schema, if any.
  String? get configureSchemaPath =>
      configureSchema == null ? null : _resolve(configureSchema!);

  /// Absolute path to the init schema, if any.
  String? get initSchemaPath =>
      initSchema == null ? null : _resolve(initSchema!);

  /// Directory for active and generated service configuration.
  String get configDir => p.join(serviceDir, 'config');

  /// Active configure payload path.
  String get activeConfigurePath => p.join(configDir, 'configure.json');

  /// Active init payload path.
  String get activeInitPath => p.join(configDir, 'init.json');

  /// Unit name expected from the primary Quadlet filename.
  String get expectedUnit =>
      '${p.basenameWithoutExtension(containerFile)}.service';

  /// Decodes [contents] from TOML.
  factory InfraServiceManifest.parse({
    required String contents,
    required String serviceDir,
    required String metadataPath,
  }) {
    final map = TomlDocument.parse(contents).toMap();
    final service = _section(map, 'service');
    final container = _section(map, 'container');
    final schemas = _optionalSection(map, 'schemas');
    final runtimeSection = _optionalSection(map, 'runtime');

    return InfraServiceManifest(
      id: _requiredString(service, 'id'),
      name: _requiredString(service, 'name'),
      unit: _requiredString(service, 'unit'),
      containerName: _requiredString(service, 'container_name'),
      runtime: InfraRuntimeKind.fromManifestValue(
        runtimeSection == null ? null : _optionalString(runtimeSection, 'type'),
      ),
      serviceDir: serviceDir,
      metadataPath: metadataPath,
      containerFile: _requiredString(container, 'file'),
      dropinsDir: _optionalString(container, 'dropins_dir'),
      profilesDir: _optionalString(container, 'profiles_dir'),
      configureSchema: schemas == null
          ? null
          : _optionalString(schemas, 'configure'),
      initSchema: schemas == null ? null : _optionalString(schemas, 'init'),
    );
  }

  /// Machine-readable summary.
  Map<String, Object?> toJson() => {
    'id': id,
    'name': name,
    'unit': unit,
    'container_name': containerName,
    'runtime': runtime.id,
    'metadata': metadataPath,
    'container_file': containerFilePath,
    'dropins_dir': dropinsDirPath,
    'profiles_dir': profilesDirPath,
    'configure_schema': configureSchemaPath,
    'init_schema': initSchemaPath,
    'active_config': activeConfigurePath,
    'active_init': activeInitPath,
  };

  String _resolve(String value) => p.isAbsolute(value)
      ? p.normalize(value)
      : p.normalize(p.join(serviceDir, value));
}

Map<String, dynamic> _section(Map<String, dynamic> map, String key) {
  final value = map[key];
  if (value is Map) {
    return value.map((key, value) => MapEntry('$key', value));
  }
  throw FormatException('metadata.toml is missing [$key].');
}

Map<String, dynamic>? _optionalSection(Map<String, dynamic> map, String key) {
  final value = map[key];
  if (value == null) return null;
  if (value is Map) {
    return value.map((key, value) => MapEntry('$key', value));
  }
  throw FormatException('metadata.toml section [$key] must be a table.');
}

String _requiredString(Map<String, dynamic> map, String key) {
  final value = _optionalString(map, key);
  if (value == null || value.isEmpty) {
    throw FormatException('metadata.toml is missing required string "$key".');
  }
  return value;
}

String? _optionalString(Map<String, dynamic> map, String key) {
  final value = map[key];
  if (value == null) return null;
  if (value is String) return value;
  throw FormatException('metadata.toml field "$key" must be a string.');
}
